#!/usr/bin/env bash
# Send one synthetic Grafana alert to the swarm's bridge, signed exactly the way
# the real contact-point integration signs one.
#
# This exists so the whole path can be proven without waiting for a real
# incident, and without turning a real alert rule loose. A run that returns 200
# proves the signature is accepted and a task was created; the incident then
# shows up in Slack like any other.
#
# Usage:
#   ./send-test-alert.sh [bridge-url]      # default: http://localhost:3014
#   ./send-test-alert.sh https://agent-swarm.goodparty.org
#
# Reads GRAFANA_WEBHOOK_SECRET and GRAFANA_BASIC_AUTH_PASSWORD from the
# AGENT_SWARM secret unless they are already exported.

set -euo pipefail

BRIDGE_URL="${1:-http://localhost:3014}"
SECRET_ID="${SECRET_ID:-AGENT_SWARM}"
REGION="${AWS_REGION:-us-west-2}"

if [[ -z "${GRAFANA_WEBHOOK_SECRET:-}" || -z "${GRAFANA_BASIC_AUTH_PASSWORD:-}" ]]; then
  read -r GRAFANA_WEBHOOK_SECRET GRAFANA_BASIC_AUTH_PASSWORD < <(
    aws secretsmanager get-secret-value --secret-id "$SECRET_ID" --region "$REGION" \
      --query SecretString --output text \
      | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['GRAFANA_WEBHOOK_SECRET'], d['GRAFANA_BASIC_AUTH_PASSWORD'])"
  )
  export GRAFANA_WEBHOOK_SECRET GRAFANA_BASIC_AUTH_PASSWORD
fi

BODY=$(python3 - <<'PY'
import json, uuid, datetime

now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
alert = {
    "status": "firing",
    "labels": {
        "alertname": "SwarmSmokeTest",
        "severity": "warning",
        "service": "agent-swarm",
        "environment": "prod",
    },
    "annotations": {
        "summary": "Synthetic alert used to prove the swarm's alert path end to end",
        "description": (
            "This alert was generated by send-test-alert.sh and does not describe a real "
            "problem. If it reaches Slack, the bridge, the signature check, the incident "
            "numbering and the task API all work. It is safe to ignore."
        ),
        "runbook_url": "https://github.com/thegoodparty/ops",
    },
    "startsAt": now,
    "endsAt": "0001-01-01T00:00:00Z",
    "generatorURL": "https://goodparty.grafana.net/alerting/list",
    # Unique per run, so each smoke test opens its own incident. A fixed one is
    # treated as a duplicate delivery inside the bridge's dedup window, which is
    # correct behaviour and useless for testing.
    "fingerprint": uuid.uuid4().hex[:16],
}
print(json.dumps([{
    "status": "firing",
    "labels": alert["labels"],
    "annotations": alert["annotations"],
    "alerts": [alert],
    "commonLabels": alert["labels"],
    "commonAnnotations": alert["annotations"],
    "externalURL": "https://goodparty.grafana.net",
}]))
PY
)

TS=$(date +%s)
# The signature is over "<timestamp>:<raw body>", hex HMAC-SHA256, which is the
# contract Grafana's own webhook integration produces.
SIG=$(printf '%s' "${TS}:${BODY}" \
  | openssl dgst -sha256 -hmac "$GRAFANA_WEBHOOK_SECRET" -hex \
  | sed 's/^.*= //')

HTTP=$(curl -sS -o /tmp/swarm-test-alert-response.txt -w '%{http_code}' \
  -X POST "$BRIDGE_URL/grafana" \
  -u "agent-swarm:${GRAFANA_BASIC_AUTH_PASSWORD}" \
  -H 'Content-Type: application/json' \
  -H "X-Grafana-Alerting-Timestamp: ${TS}" \
  -H "X-Grafana-Alerting-Signature: ${SIG}" \
  --data-binary "$BODY")

echo "HTTP ${HTTP}"
cat /tmp/swarm-test-alert-response.txt 2>/dev/null || true
echo
if [[ "$HTTP" == "200" || "$HTTP" == "201" || "$HTTP" == "202" ]]; then
  echo "accepted: an incident should now be open in the incident channel"
else
  echo "rejected. check the bridge log, then that the secret matches the integration" >&2
  exit 1
fi
